import React, { useState, useEffect, useRef } from 'react'

// Simple SHA-256 hash helper for PIN storage async function sha256Hex(input) { const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(input)) return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('') }

export default function PhantomVault() { const containerRef = useRef(null) const [unlocked, setUnlocked] = useState(false) const [inputPin, setInputPin] = useState('') const [storedPinHash, setStoredPinHash] = useState(null) const [wrongCount, setWrongCount] = useState(0) const [lockoutTimer, setLockoutTimer] = useState(0) const [currentTab, setCurrentTab] = useState('files')

// Load or initialize hashed PIN useEffect(() => { ;(async () => { const stored = localStorage.getItem('phantom.pinHash') if (stored) setStoredPinHash(stored) else { const hash = await sha256Hex('password') // default PIN localStorage.setItem('phantom.pinHash', hash) setStoredPinHash(hash) } })() }, [])

// Handle PIN input const handlePinKey = async (key) => { if (lockoutTimer > 0) return const next = inputPin + key setInputPin(next) if (next.length === 4) { const hash = await sha256Hex(next) if (hash === storedPinHash) { setUnlocked(true) setInputPin('') setWrongCount(0) setCurrentTab('files') } else { setWrongCount(prev => prev + 1) setInputPin('') if (wrongCount + 1 >= 5) { setLockoutTimer(60) // 60s lockout } } } }

// Lockout countdown useEffect(() => { if (lockoutTimer <= 0) return const interval = setInterval(() => { setLockoutTimer(prev => { if (prev <= 1) return 0 return prev - 1 }) }, 1000) return () => clearInterval(interval) }, [lockoutTimer])

// Shake-to-exit listener useEffect(() => { const handleMotion = (e) => { const { x, y, z } = e.accelerationIncludingGravity if (Math.abs(x) + Math.abs(y) + Math.abs(z) > 30) setUnlocked(false) } if (typeof DeviceMotionEvent !== 'undefined' && DeviceMotionEvent.requestPermission) { DeviceMotionEvent.requestPermission().then(response => { if (response === 'granted') window.addEventListener('devicemotion', handleMotion) }) } else { window.addEventListener('devicemotion', handleMotion) } return () => window.removeEventListener('devicemotion', handleMotion) }, [])

// Render PIN entry if (!unlocked) { return ( <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}> <h2>Enter PIN</h2> {lockoutTimer > 0 ? ( <p>Locked! {lockoutTimer}s remaining</p> ) : ( <div> {[1,2,3,4,5,6,7,8,9,0].map(n => ( <button key={n} onClick={() => handlePinKey(n.toString())}>{n}</button> ))} </div> )} </div> ) }

// Render unlocked vault return ( <div ref={containerRef} style={{ height: '100vh', overflowY: 'auto', padding: '10px' }}> <header style={{ marginBottom: '10px' }}> <h1>Phantom Vault v2</h1> <nav> {['files','notes','passwords','logs','settings'].map(tab => ( <button key={tab} onClick={() => setCurrentTab(tab)}>{tab.toUpperCase()}</button> ))} </nav> </header> <main style={{ minHeight: '80vh' }}> {currentTab === 'files' && <div>Files Tab Content</div>} {currentTab === 'notes' && <div>Secret Notes Content</div>} {currentTab === 'passwords' && <div>Password Manager Content</div>} {currentTab === 'logs' && <div>Activity Log Content</div>} {currentTab === 'settings' && <div>Settings Content</div>} </main> <footer> <button onClick={() => setUnlocked(false)}>Fast Exit</button> </footer> </div> ) }
